aws:
  region: us-east-1
  kms:
    key-id: arn:aws:kms:us-east-1:948976367185:key/70e01ce3-5b37-4632-86c9-88836af6cb1e
    alias-name: alias/springboot-dynamic-key-kmsTue
    keyCreationProcess: DYNAMIC
  credentials:
    access-key:        # optional (use for local only)
    secret-key:     # optional (use for local only)

logging:
  level:
    software.amazon.awssdk: DEBUG
    software.amazon.awssdk.services.kms: DEBUG