server:
  port: 8085

aws:
  region: us-east-1

  # KMS Configuration
  kms:
    key-id: arn:aws:kms:us-east-1:948976367185:key/6add9659-b426-4dd8-8a12-8297b720e90f
    assume-role-arn: arn:aws:iam::<ACCOUNT_ID>:role/kms-key-creator-role
    alias-name: alias/springboot-dynamic-key-kmsTue
    keyCreationProcess: CONSOLE

  # Credentials (for local development only)
  credentials:
    access-key: AKIA5Z43GGZIX257TNFE          # ⚠️ Optional: local testing only
    secret-key: A17xmu53kyYl1nxh5O3/qL71VzaeJQ3x0lRPWaWH  # ⚠️ Optional: local testing only

logging:
  level:
    root: INFO
    software.amazon.awssdk: DEBUG
    software.amazon.awssdk.services.kms: DEBUG
